'Task 1'
X = 50
Y= 19.99
K = 'VERA'
Z = True

print(X)
print(Y)
print(K)
print(Z)

'Task 2'
float_to_int = int(Y)
print("Converted float to int:", float_to_int, "Type:", type(float_to_int))
int_to_str = str(X)
print("Converted int to str:", int_to_str, "Type", type(int_to_str))
str_to_float = float("50")
print("Converted str to float:", str_to_float, "Type:", type(str_to_float))

'Task 3'
First_Name = input("What's Your First Name?")
Last_Name = input("What's Your Last Name?")
print("Hello,", First_Name, Last_Name)

'Task 4'
age = 20
print("You are", age, "years old.")

"The error before correction was a TypeError"

'Task 5'
Favorite_Word = input("What's Your Favorite Word?")
repeat_count = int(input("How many times would you like to repeat it?"))
print((Favorite_Word,) * repeat_count)


'Tasks 6'
'a.  print("Hello  = SyntaxError '
'b.  int("abc")    = ValueError '
'c.  "age" + 10    = TypeError '
